[package]
name = "spacetimedsl_test"
version = "0.8.2"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
# https://crates.io/crates/proc_macro2 A substitute implementation of the compiler's `proc_macro` API to decouple token-based libraries from the procedural macro use case.
proc-macro2 = { version = "1", features = ["span-locations"] }

# https://crates.io/crates/spacetimedb Easy support for interacting between SpacetimeDB and Rust.
spacetimedb = "1.2.0"

# https://crates.io/crates/syn Parser for Rust source code
syn = { default-features = false, features = [
    "extra-traits",
    "full",
    "parsing",
], version = "2.0.103" }

# https://crates.io/crates/spacetimedsl Ergonomic DSL for SpacetimeDB
spacetimedsl = { version = "0.8.2", path = "../" }

# https://crates.io/crates/log A lightweight logging facade for Rust
log = "0.4"
