[package]
authors = ["Tamaro Skaljic<mail@tamaro-skaljic.de>"]
name = "spacetimedsl"
version = "0.16.0"
edition = "2024"
description = "Ergonomic DSL for SpacetimeDB"
documentation = "https://docs.rs/spacetimedsl"
license = "MIT OR Apache-2.0"
repository = "https://github.com/tamaro-skaljic/SpacetimeDSL"
publish = true
include = ["README.md", "/src/**"]
keywords = ["dsl", "spacetime", "macro", "codegen", "boilerplate"]
readme = "README.md"

[dependencies]
# https://crates.io/crates/spacetimedb Easy support for interacting between SpacetimeDB and Rust.
spacetimedb = { version = "1.12.0", features = ["unstable"] }

# https://crates.io/crates/spacetimedsl_derive Macros to extend SpacetimeDSL
spacetimedsl_derive = { version = "0.16.0", path = "derive" }

# https://crates.io/crates/itertools Extra iterator adaptors, iterator methods, free functions, and macros.
itertools = "^0.14"

[workspace]
members = [
    "debug-helper",
    "derive-input",
    "derive",
    "examples/test",
    "examples/blackholio",
]
