#!/bin/bash

# Helper functions that return shell-specific syntax


switch_start() {
    case "$1" in
        bash) echo 'case "$1" in' ;;
        powershell) echo 'switch ($Command) {' ;;
    esac
}

switch_case() {
    local shell="$1"
    local case_name="$2"
    case "$shell" in
        bash) echo "    $case_name)" ;;
        powershell) echo "    \"$case_name\" {" ;;
    esac
}

switch_case_end() {
    case "$1" in
        bash) echo "        ;;" ;;
        powershell) echo "    }" ;;
    esac
}

switch_default() {
    case "$1" in
        bash) echo "    *)" ;;
        powershell) echo "    default {" ;;
    esac
}

switch_end() {
    case "$1" in
        bash) echo "esac" ;;
        powershell) echo "}" ;;
    esac
}

cmd_echo() {
    local shell="$1"
    local text="$2"
    case "$shell" in
        bash)
            if [ -z "$text" ]; then
                echo "        echo"
            else
                echo "        echo \"$text\""
            fi
            ;;
        powershell)
            if [ -z "$text" ]; then
                echo "        Write-Output \"\""
            else
                echo "        Write-Output \"$text\""
            fi
            ;;
    esac
}

cmd_cd() {
    local shell="$1"
    local path="$2"
    case "$shell" in
        bash)
            if [[ "$path" == ".." || "$path" == "../.." ]]; then
                echo "        popd > /dev/null"
            else
                echo "        pushd $path > /dev/null"
            fi
            ;;
        powershell)
            if [[ "$path" == ".." || "$path" == "../.." ]]; then
                echo "        Pop-Location"
            else
                echo "        Push-Location ${path//\//\\}"
            fi
            ;;
    esac
}

script_usage() {
    local shell="$1"
    case "$shell" in
        bash) echo "./x" ;;
        powershell) echo ".\\x.ps1" ;;
    esac
}

indent() {
    local shell="$1"
    local level="${2:-1}"
    local spaces=$((level * 4))
    printf "%${spaces}s" ""
}

# Generate common commands that are the same across shells
cmd_spacetime() {
    local shell="$1"
    local command="$2"
    echo "        spacetime $command"
    if [ "$shell" = "powershell" ]; then
        echo "        if (\$LASTEXITCODE -ne 0) { throw \"spacetime $command failed\" }"
    fi
}

cmd_cargo() {
    local shell="$1"
    local command="$2"
    echo "        cargo $command"
    if [ "$shell" = "powershell" ]; then
        echo "        if (\$LASTEXITCODE -ne 0) { throw \"cargo $command failed\" }"
    fi
}

cmd_logs_with_marker() {
    local shell="$1"
    local module="$2"
    if [ "$shell" = "bash" ]; then
        echo "        test_logs=\$(spacetime logs --yes --server local $module)"
        echo "        printf '%s\\n' \"\$test_logs\""
        echo "        grep -Fq 'Test executed successfully' <<< \"\$test_logs\" || { echo \"Test marker missing from $module logs\" >&2; exit 1; }"
    else
        echo "        \$test_logs = spacetime logs --yes --server local $module"
        echo "        if (\$LASTEXITCODE -ne 0) { throw \"spacetime logs for $module failed\" }"
        echo "        \$test_logs"
        echo "        if (\$test_logs -notmatch 'Test executed successfully') { throw \"Test marker missing from $module logs\" }"
    fi
}

# Header and case generation functions
generate_header() {
    local shell="$1"

    local do_not_change="# This file is generated by gen-x.sh. Do not change it directly."

    if [ "$shell" = "bash" ]; then
        # Bash shebang
        echo "#!/bin/bash"
        echo
        echo "$do_not_change"
        echo "set -euo pipefail"
    else
        # PowerShell param block
        echo "$do_not_change"
        echo
        cat << 'EOF'
param(
    [Parameter(Position=0)]
    [ArgumentCompleter({
        param($commandName, $parameterName, $wordToComplete)
        "test", "unit-test", "format", "lint", "debug", "loc" | Where-Object { $_ -like "$wordToComplete*" }
    })]
    [string]$Command
)
EOF
        echo "\$ErrorActionPreference = 'Stop'"
        echo "\$ErrorActionPreference = 'Continue'"
    fi

    echo

    if [ "$shell" = "bash" ]; then
        cat << 'EOF'
wait_for_server() {
    for attempt in {1..30}; do
        if spacetime server ping local >/dev/null 2>&1; then
            return
        fi
        sleep 1
    done
    echo "Local SpacetimeDB server is unavailable; run 'spacetime start'." >&2
    return 1
}
EOF
    else
        cat << 'EOF'
function Wait-ForServer {
    for ($attempt = 1; $attempt -le 30; $attempt++) {
        $previousErrorActionPreference = $ErrorActionPreference
        $ErrorActionPreference = 'Continue'
        spacetime server ping local *> $null
        $pingExitCode = $LASTEXITCODE
        $ErrorActionPreference = $previousErrorActionPreference
        if ($pingExitCode -eq 0) {
            return
        }
        Start-Sleep -Seconds 1
    }
    throw "Local SpacetimeDB server is unavailable; run 'spacetime start'."
}
EOF
    fi
}

# Every `spacetime` command passes `--yes`, because CI runs this case on a runner
# which is not logged in and has no terminal to answer a prompt on.
generate_test() {
    local shell="$1"

    switch_case "$shell" "test"
    if [ "$shell" = "bash" ]; then
        echo "        wait_for_server"
        cat << 'EOF'
        cleanup_modules() {
            spacetime delete --yes --server local spacetimedsl >/dev/null 2>&1 || true
            spacetime delete --yes --server local blackholio >/dev/null 2>&1 || true
        }
        trap cleanup_modules EXIT
EOF
    else
        echo "        Wait-ForServer"
        echo "        \$originalLocation = (Get-Location).Path"
        echo "        try {"
    fi
    cmd_echo "$shell" "Building module..."
    cmd_echo "$shell"
    cmd_cd "$shell" "examples/test"
    cmd_spacetime "$shell" "publish --yes --server local spacetimedsl"
    cmd_echo "$shell"
    echo
    cmd_echo "$shell" "Testing module..."
    cmd_echo "$shell"
    cmd_spacetime "$shell" "call --yes --server local spacetimedsl tester"
    echo
    cmd_echo "$shell" "Showing logs..."
    cmd_echo "$shell"
    cmd_logs_with_marker "$shell" "spacetimedsl"
    cmd_echo "$shell"
    echo
    cmd_echo "$shell" "Cleaning up module..."
    cmd_echo "$shell"
    cmd_spacetime "$shell" "delete --yes --server local spacetimedsl"
    cmd_cd "$shell" "../.."

    cmd_echo "$shell" "Building module..."
    cmd_echo "$shell"
    cmd_cd "$shell" "examples/blackholio"
    cmd_spacetime "$shell" "publish --yes --server local blackholio"
    cmd_echo "$shell"
    echo
    cmd_echo "$shell" "Showing logs..."
    cmd_echo "$shell"
    cmd_logs_with_marker "$shell" "blackholio"
    cmd_echo "$shell"
    echo
    cmd_echo "$shell" "Cleaning up module..."
    cmd_echo "$shell"
    cmd_spacetime "$shell" "delete --yes --server local blackholio"
    cmd_cd "$shell" "../.."

    if [ "$shell" = "powershell" ]; then
        cat << 'EOF'
        } finally {
            $previousErrorActionPreference = $ErrorActionPreference
            $ErrorActionPreference = 'Continue'
            spacetime delete --yes --server local spacetimedsl *> $null
            spacetime delete --yes --server local blackholio *> $null
            while ((Get-Location).Path -ne $originalLocation) {
                Pop-Location
            }
            $ErrorActionPreference = $previousErrorActionPreference
        }
EOF
    fi

    switch_case_end "$shell"
    echo
}

generate_unit_test() {
    local shell="$1"

    switch_case "$shell" "unit-test"
    cmd_echo "$shell" "Snapshotting the generated code..."
    cmd_echo "$shell"
    cmd_cargo "$shell" "test -p spacetimedsl_derive"
    cmd_echo "$shell"
    echo
    cmd_echo "$shell" "Checking the diagnostics for rejected tables..."
    cmd_echo "$shell"
    cmd_cargo "$shell" "test -p spacetimedsl-compile-tests"
    switch_case_end "$shell"
    echo
}

# Clippy runs once over the whole workspace rather than once per directory, because
# `cargo clippy` does not lint dependencies: running it in `derive/` checks that package
# only, which left `derive-input/` -- the crate holding most of the generator -- unlinted.
generate_format() {
    local shell="$1"

    switch_case "$shell" "format"
    cmd_cargo "$shell" "fmt --all"
    echo
    cmd_cargo "$shell" "clippy --workspace --all-targets --all-features --fix --allow-dirty"
    switch_case_end "$shell"
    echo
}

generate_lint() {
    local shell="$1"

    switch_case "$shell" "lint"
    cmd_cargo "$shell" "fmt --all -- --check"
    cmd_cargo "$shell" "clippy --workspace --all-targets --all-features -- -D warnings"
    switch_case_end "$shell"
    echo
}

generate_debug() {
    local shell="$1"

    switch_case "$shell" "debug"
    cmd_cd "$shell" "examples/test"
    if [ "$shell" = "bash" ]; then
        echo "        RUSTFLAGS=\"-Zmacro-backtrace\" cargo +nightly expand > ../../debug-helper/output/lib.expanded.rs"
    else
        echo "        \$previousRustflags = \$env:RUSTFLAGS"
        echo "        try {"
        echo "        \$env:RUSTFLAGS = \"-Zmacro-backtrace\""
        echo "        cargo +nightly expand > ..\\..\\debug-helper\\output\\lib.expanded.rs"
        echo "        if (\$LASTEXITCODE -ne 0) { throw 'cargo expand failed' }"
        echo "        } finally { \$env:RUSTFLAGS = \$previousRustflags }"
    fi
    cmd_cd "$shell" "../../debug-helper"
    if [ "$shell" = "bash" ]; then
        echo "        cargo run -- ../examples/test/src output"
    else
        echo "        cargo run -- ..\\examples\\test\\src output"
    fi
    cmd_cd "$shell" ".."
    switch_case_end "$shell"
    echo
}

generate_loc() {
    local shell="$1"

    switch_case "$shell" "loc"
    if [ "$shell" = "bash" ]; then
        cat << 'BASH_LOC'
        while IFS= read -r file; do
            lines=$(wc -l < "$file")

            rel_path="${file#./}"

            first_dir="${rel_path%%/*}"

            path_without_first="${rel_path#*/}"

            if [[ "$path_without_first" == src/* ]]; then
                path_without_first="${path_without_first#src/}"
            fi

            echo "$first_dir|$lines|$path_without_first"
        done < <(find . -path "*/src/*.rs" -type f) | sort -t'|' -k1,1 -k2,2nr | {
            current_group=""
            total=0

            while IFS='|' read -r first_dir lines path_without_first; do
                # Track total for src, derive-input, derive
                if [[ "$first_dir" == "src" || "$first_dir" == "derive-input" || "$first_dir" == "derive" ]]; then
                    total=$((total + lines))
                fi

                # Print group header when directory changes
                if [[ "$current_group" != "$first_dir" ]]; then
                    if [[ -n "$current_group" ]]; then
                        echo
                    fi
                    echo "$first_dir:"
                    current_group="$first_dir"
                fi

                # Print with padding
                printf "%6d %s\n" "$lines" "$path_without_first"
            done

            echo
            echo "Total: $total"
            echo
        }
BASH_LOC
    else
        cat << 'POWERSHELL_LOC'
        $files = Get-ChildItem -Path . -Filter "*.rs" -Recurse -File | Where-Object {
            $_.FullName -like "*\src\*"
        } | ForEach-Object {
            $lineCount = (Get-Content $_.FullName | Measure-Object -Line).Lines

            $relativePath = $_.FullName.Replace("$PWD\", "")
            $firstDir = $relativePath.Split('\')[0]
            $pathWithoutFirstDir = $relativePath.Substring($firstDir.Length + 1)

            if ($pathWithoutFirstDir.StartsWith("src\")) {
                $pathWithoutFirstDir = $pathWithoutFirstDir.Substring(4)
            }

            $secondDir = if ($pathWithoutFirstDir.Contains('\')) {
                $pathWithoutFirstDir.Split('\')[0]
            } else {
                ""
            }

            [PSCustomObject]@{
                Lines = $lineCount
                Path = $relativePath
                FirstDir = $firstDir
                SecondDir = $secondDir
                PathWithoutFirstDir = $pathWithoutFirstDir
            }
        } | Sort-Object -Property FirstDir, SecondDir, @{Expression = {$_.Lines}; Descending = $true}

        $maxLineLength = ($files | ForEach-Object { $_.Lines.ToString().Length } | Measure-Object -Maximum).Maximum

        $currentGroup = $null
        $files | ForEach-Object {
            if ($currentGroup -ne $_.FirstDir) {
                if ($currentGroup -ne $null) {
                    Write-Output ""
                }
                Write-Output "$($_.FirstDir):"
                $currentGroup = $_.FirstDir
            }

            $paddedLines = $_.Lines.ToString().PadLeft($maxLineLength)
            Write-Output "$paddedLines $($_.PathWithoutFirstDir)"
        }

        $total = ($files | Where-Object { $_.FirstDir -in @("src", "derive-input", "derive") } | Measure-Object -Property Lines -Sum).Sum
        Write-Output "Total: $total"

        Write-Output ""
POWERSHELL_LOC
    fi
    switch_case_end "$shell"
    echo
}

generate_usage() {
    local shell="$1"

    switch_default "$shell"
    cmd_echo "$shell" "Usage: $(script_usage "$shell") {test|unit-test|format|lint|debug|loc}"
    cmd_echo "$shell"
    cmd_echo "$shell" "Commands:"
    cmd_echo "$shell" "  test      - Publish and test the test module, then publish blackholio"
    cmd_echo "$shell" "  unit-test - Run the snapshot and compile tests of the generator"
    cmd_echo "$shell" "  format    - Format the code and apply clippy fixes"
    cmd_echo "$shell" "  lint      - Check formatting and lint the whole workspace"
    cmd_echo "$shell" "  debug     - Expand macros and generate AST output"
    cmd_echo "$shell" "  loc       - Count lines of Rust code grouped by directory"
    echo "        exit 1"
    switch_case_end "$shell"
}

# Main generation function
generate() {
    local shell="$1"

    generate_header "$shell"
    switch_start "$shell"
    generate_test "$shell"
    generate_unit_test "$shell"
    generate_format "$shell"
    generate_lint "$shell"
    generate_debug "$shell"
    generate_loc "$shell"
    generate_usage "$shell"
    switch_end "$shell"
}

# Main script execution
echo "Generating x.sh (bash)..."
generate bash > x.sh
chmod +x x.sh

echo "Generating x.ps1 (PowerShell)..."
generate powershell > x.ps1

echo "Done! Generated x.sh and x.ps1"
