#!/bin/bash

# Helper functions that return shell-specific syntax


switch_start() {
    case "$1" in
        bash) echo 'case "${1:-}" in' ;;
        powershell) echo 'switch ($Command) {' ;;
    esac
}

switch_case() {
    local shell="$1"
    local case_name="$2"
    case "$shell" in
        bash) echo "    $case_name)" ;;
        powershell) echo "    \"$case_name\" {" ;;
    esac
}

switch_case_end() {
    case "$1" in
        bash) echo "        ;;" ;;
        powershell) echo "    }" ;;
    esac
}

switch_default() {
    case "$1" in
        bash) echo "    *)" ;;
        powershell) echo "    default {" ;;
    esac
}

switch_end() {
    case "$1" in
        bash) echo "esac" ;;
        powershell) echo "}" ;;
    esac
}

cmd_echo() {
    local shell="$1"
    local text="$2"
    case "$shell" in
        bash)
            if [ -z "$text" ]; then
                echo "        echo"
            else
                echo "        echo \"$text\""
            fi
            ;;
        powershell)
            if [ -z "$text" ]; then
                echo "        Write-Output \"\""
            else
                echo "        Write-Output \"$text\""
            fi
            ;;
    esac
}

script_usage() {
    local shell="$1"
    case "$shell" in
        bash) echo "./x.sh" ;;
        powershell) echo ".\\x.ps1" ;;
    esac
}

# A native command whose failure ends the script. Bash stops through `set -e`;
# PowerShell does not stop on a native exit code, so it checks `$LASTEXITCODE`.
cmd_native() {
    local shell="$1"
    local command="$2"
    echo "        $command"
    if [ "$shell" = "powershell" ]; then
        echo "        if (\$LASTEXITCODE -ne 0) { throw \"'$command' failed with exit code \$LASTEXITCODE.\" }"
    fi
}

# Header and case generation functions
generate_header() {
    local shell="$1"

    local do_not_change="# This file is generated by gen-x.sh. Do not change it directly."

    if [ "$shell" = "bash" ]; then
        echo "#!/bin/bash"
        echo
        echo "$do_not_change"
        echo
        echo "set -euo pipefail"
    else
        echo "$do_not_change"
        echo
        cat << 'EOF'
param(
    [Parameter(Position=0)]
    [ArgumentCompleter({
        param($commandName, $parameterName, $wordToComplete)
        "test", "unit-test", "format", "lint", "debug", "loc" | Where-Object { $_ -like "$wordToComplete*" }
    })]
    [string]$Command
)

$ErrorActionPreference = 'Stop'

# A thrown error ends the script with exit code 1, so callers can rely on `$LASTEXITCODE`.
trap {
    [Console]::Error.WriteLine("x.ps1 $Command failed: $_")
    exit 1
}
EOF
    fi

    echo
}

# Every `spacetime` command passes `--yes`, because CI runs this case on a runner
# which is not logged in and has no terminal to answer a prompt on.
generate_test() {
    local shell="$1"

    switch_case "$shell" "test"
    if [ "$shell" = "bash" ]; then
        cat << 'BASH_TEST'
        echo "Waiting for the local server..."
        deadline=$((SECONDS + 30))
        until spacetime server ping local > /dev/null 2>&1; do
            if [ "$SECONDS" -ge "$deadline" ]; then
                echo "The local server is still unreachable after 30 seconds. Start it with 'spacetime start'." >&2
                exit 1
            fi
            sleep 1
        done
        echo

        echo "Building module..."
        echo
        pushd examples/test > /dev/null
        trap 'spacetime delete --yes --server local spacetimedsl > /dev/null 2>&1 || true' EXIT
        spacetime publish --yes --server local spacetimedsl
        echo

        echo "Testing module..."
        echo
        tester_exit_code=0
        spacetime call --yes --server local spacetimedsl tester || tester_exit_code=$?

        echo "Showing logs..."
        echo
        logs=$(spacetime logs --yes --server local spacetimedsl)
        echo "$logs"
        echo
        if [ "$tester_exit_code" -ne 0 ]; then
            echo "'spacetime call --yes --server local spacetimedsl tester' failed with exit code $tester_exit_code." >&2
            exit 1
        fi
        if ! grep -qF "Test executed successfully" <<< "$logs"; then
            echo "The logs of spacetimedsl do not contain 'Test executed successfully'." >&2
            exit 1
        fi

        echo "Cleaning up module..."
        echo
        spacetime delete --yes --server local spacetimedsl
        trap - EXIT
        popd > /dev/null

        echo "Building module..."
        echo
        pushd examples/blackholio > /dev/null
        trap 'spacetime delete --yes --server local blackholio > /dev/null 2>&1 || true' EXIT
        spacetime publish --yes --server local blackholio
        echo

        echo "Showing logs..."
        echo
        spacetime logs --yes --server local blackholio
        echo

        echo "Cleaning up module..."
        echo
        spacetime delete --yes --server local blackholio
        trap - EXIT
        popd > /dev/null
BASH_TEST
    else
        cat << 'POWERSHELL_TEST'
        Write-Output "Waiting for the local server..."
        $deadline = (Get-Date).AddSeconds(30)
        while ($true) {
            spacetime server ping local *> $null
            if ($LASTEXITCODE -eq 0) { break }
            if ((Get-Date) -gt $deadline) {
                throw "The local server is still unreachable after 30 seconds. Start it with 'spacetime start'."
            }
            Start-Sleep -Seconds 1
        }
        Write-Output ""

        Push-Location examples\test
        try {
            Write-Output "Building module..."
            Write-Output ""
            spacetime publish --yes --server local spacetimedsl
            if ($LASTEXITCODE -ne 0) { throw "'spacetime publish --yes --server local spacetimedsl' failed with exit code $LASTEXITCODE." }
            Write-Output ""

            Write-Output "Testing module..."
            Write-Output ""
            spacetime call --yes --server local spacetimedsl tester
            $testerExitCode = $LASTEXITCODE

            Write-Output "Showing logs..."
            Write-Output ""
            $logs = spacetime logs --yes --server local spacetimedsl
            if ($LASTEXITCODE -ne 0) { throw "'spacetime logs --yes --server local spacetimedsl' failed with exit code $LASTEXITCODE." }
            $logs
            Write-Output ""
            if ($testerExitCode -ne 0) {
                throw "'spacetime call --yes --server local spacetimedsl tester' failed with exit code $testerExitCode."
            }
            if (-not ($logs | Select-String -SimpleMatch "Test executed successfully" -Quiet)) {
                throw "The logs of spacetimedsl do not contain 'Test executed successfully'."
            }

            Write-Output "Cleaning up module..."
            Write-Output ""
            spacetime delete --yes --server local spacetimedsl
            if ($LASTEXITCODE -ne 0) { throw "'spacetime delete --yes --server local spacetimedsl' failed with exit code $LASTEXITCODE." }
        } catch {
            spacetime delete --yes --server local spacetimedsl *> $null
            throw
        } finally {
            Pop-Location
        }

        Push-Location examples\blackholio
        try {
            Write-Output "Building module..."
            Write-Output ""
            spacetime publish --yes --server local blackholio
            if ($LASTEXITCODE -ne 0) { throw "'spacetime publish --yes --server local blackholio' failed with exit code $LASTEXITCODE." }
            Write-Output ""

            Write-Output "Showing logs..."
            Write-Output ""
            spacetime logs --yes --server local blackholio
            if ($LASTEXITCODE -ne 0) { throw "'spacetime logs --yes --server local blackholio' failed with exit code $LASTEXITCODE." }
            Write-Output ""

            Write-Output "Cleaning up module..."
            Write-Output ""
            spacetime delete --yes --server local blackholio
            if ($LASTEXITCODE -ne 0) { throw "'spacetime delete --yes --server local blackholio' failed with exit code $LASTEXITCODE." }
        } catch {
            spacetime delete --yes --server local blackholio *> $null
            throw
        } finally {
            Pop-Location
        }
POWERSHELL_TEST
    fi
    switch_case_end "$shell"
    echo
}

generate_unit_test() {
    local shell="$1"

    switch_case "$shell" "unit-test"
    cmd_echo "$shell" "Snapshotting the generated code..."
    cmd_echo "$shell"
    cmd_native "$shell" "cargo test -p spacetimedsl_derive"
    cmd_echo "$shell"
    echo
    cmd_echo "$shell" "Checking the diagnostics for rejected tables..."
    cmd_echo "$shell"
    cmd_native "$shell" "cargo test -p spacetimedsl-compile-tests"
    switch_case_end "$shell"
    echo
}

# Clippy runs once over the whole workspace rather than once per directory, because
# `cargo clippy` does not lint dependencies: running it in `derive/` checks that package
# only, which left `derive-input/` -- the crate holding most of the generator -- unlinted.
generate_format() {
    local shell="$1"

    switch_case "$shell" "format"
    cmd_native "$shell" "cargo fmt --all"
    echo
    cmd_native "$shell" "cargo clippy --workspace --all-targets --all-features --fix --allow-dirty"
    switch_case_end "$shell"
    echo
}

# The check-only counterpart of `format`, which CI runs: it changes no file and fails on
# unformatted code or on any clippy warning, over the same whole workspace.
generate_lint() {
    local shell="$1"

    switch_case "$shell" "lint"
    cmd_native "$shell" "cargo fmt --all -- --check"
    echo
    cmd_native "$shell" "cargo clippy --workspace --all-targets --all-features -- -D warnings"
    switch_case_end "$shell"
    echo
}

# `-Zmacro-backtrace` applies to the expansion only, so the PowerShell variant restores RUSTFLAGS
# afterwards instead of leaving it set for every later build in the same session.
generate_debug() {
    local shell="$1"

    switch_case "$shell" "debug"
    if [ "$shell" = "bash" ]; then
        cat << 'BASH_DEBUG'
        pushd examples/test > /dev/null
        RUSTFLAGS="-Zmacro-backtrace" cargo +nightly expand > ../../debug-helper/output/lib.expanded.rs
        popd > /dev/null
        pushd debug-helper > /dev/null
        cargo run -- ../examples/test/src output
        popd > /dev/null
BASH_DEBUG
    else
        cat << 'POWERSHELL_DEBUG'
        $previousRustFlags = $env:RUSTFLAGS
        Push-Location examples\test
        try {
            $env:RUSTFLAGS = "-Zmacro-backtrace"
            cargo +nightly expand > ..\..\debug-helper\output\lib.expanded.rs
            if ($LASTEXITCODE -ne 0) { throw "'cargo +nightly expand' failed with exit code $LASTEXITCODE." }
        } finally {
            $env:RUSTFLAGS = $previousRustFlags
            Pop-Location
        }
        Push-Location debug-helper
        try {
            cargo run -- ..\examples\test\src output
            if ($LASTEXITCODE -ne 0) { throw "'cargo run -- ..\examples\test\src output' failed with exit code $LASTEXITCODE." }
        } finally {
            Pop-Location
        }
POWERSHELL_DEBUG
    fi
    switch_case_end "$shell"
    echo
}

generate_loc() {
    local shell="$1"

    switch_case "$shell" "loc"
    if [ "$shell" = "bash" ]; then
        cat << 'BASH_LOC'
        while IFS= read -r file; do
            lines=$(wc -l < "$file")

            rel_path="${file#./}"

            first_dir="${rel_path%%/*}"

            path_without_first="${rel_path#*/}"

            if [[ "$path_without_first" == src/* ]]; then
                path_without_first="${path_without_first#src/}"
            fi

            echo "$first_dir|$lines|$path_without_first"
        done < <(find . -path "*/src/*.rs" -type f) | sort -t'|' -k1,1 -k2,2nr | {
            current_group=""
            total=0

            while IFS='|' read -r first_dir lines path_without_first; do
                if [[ "$first_dir" == "src" || "$first_dir" == "derive-input" || "$first_dir" == "derive" ]]; then
                    total=$((total + lines))
                fi

                if [[ "$current_group" != "$first_dir" ]]; then
                    if [[ -n "$current_group" ]]; then
                        echo
                    fi
                    echo "$first_dir:"
                    current_group="$first_dir"
                fi

                printf "%6d %s\n" "$lines" "$path_without_first"
            done

            echo
            echo "Total: $total"
            echo
        }
BASH_LOC
    else
        cat << 'POWERSHELL_LOC'
        $files = Get-ChildItem -Path . -Filter "*.rs" -Recurse -File | Where-Object {
            $_.FullName -like "*\src\*"
        } | ForEach-Object {
            $lineCount = (Get-Content $_.FullName | Measure-Object -Line).Lines

            $relativePath = $_.FullName.Replace("$PWD\", "")
            $firstDir = $relativePath.Split('\')[0]
            $pathWithoutFirstDir = $relativePath.Substring($firstDir.Length + 1)

            if ($pathWithoutFirstDir.StartsWith("src\")) {
                $pathWithoutFirstDir = $pathWithoutFirstDir.Substring(4)
            }

            $secondDir = if ($pathWithoutFirstDir.Contains('\')) {
                $pathWithoutFirstDir.Split('\')[0]
            } else {
                ""
            }

            [PSCustomObject]@{
                Lines = $lineCount
                Path = $relativePath
                FirstDir = $firstDir
                SecondDir = $secondDir
                PathWithoutFirstDir = $pathWithoutFirstDir
            }
        } | Sort-Object -Property FirstDir, SecondDir, @{Expression = {$_.Lines}; Descending = $true}

        $maxLineLength = ($files | ForEach-Object { $_.Lines.ToString().Length } | Measure-Object -Maximum).Maximum

        $currentGroup = $null
        $files | ForEach-Object {
            if ($currentGroup -ne $_.FirstDir) {
                if ($currentGroup -ne $null) {
                    Write-Output ""
                }
                Write-Output "$($_.FirstDir):"
                $currentGroup = $_.FirstDir
            }

            $paddedLines = $_.Lines.ToString().PadLeft($maxLineLength)
            Write-Output "$paddedLines $($_.PathWithoutFirstDir)"
        }

        $total = ($files | Where-Object { $_.FirstDir -in @("src", "derive-input", "derive") } | Measure-Object -Property Lines -Sum).Sum
        Write-Output "Total: $total"

        Write-Output ""
POWERSHELL_LOC
    fi
    switch_case_end "$shell"
    echo
}

generate_usage() {
    local shell="$1"

    switch_default "$shell"
    cmd_echo "$shell" "Usage: $(script_usage "$shell") {test|unit-test|format|lint|debug|loc}"
    cmd_echo "$shell"
    cmd_echo "$shell" "Commands:"
    cmd_echo "$shell" "  test      - Publish and test the 'test' module (fails unless its logs show success), then publish 'blackholio'"
    cmd_echo "$shell" "  unit-test - Run the snapshot and compile tests of the generator"
    cmd_echo "$shell" "  format    - Format the code and apply clippy fixes"
    cmd_echo "$shell" "  lint      - Check formatting and fail on any clippy warning, as CI does"
    cmd_echo "$shell" "  debug     - Expand macros and generate AST output"
    cmd_echo "$shell" "  loc       - Count lines of Rust code grouped by directory"
    echo "        exit 1"
    switch_case_end "$shell"
}

# Main generation function
generate() {
    local shell="$1"

    generate_header "$shell"
    switch_start "$shell"
    generate_test "$shell"
    generate_unit_test "$shell"
    generate_format "$shell"
    generate_lint "$shell"
    generate_debug "$shell"
    generate_loc "$shell"
    generate_usage "$shell"
    switch_end "$shell"
}

# Main script execution
echo "Generating x.sh (bash)..."
generate bash > x.sh
chmod +x x.sh

echo "Generating x.ps1 (PowerShell)..."
generate powershell > x.ps1

echo "Done! Generated x.sh and x.ps1"
