# This file is generated by gen-x.sh. Do not change it directly.

param(
    [Parameter(Position=0)]
    [ArgumentCompleter({
        param($commandName, $parameterName, $wordToComplete)
        "test", "unit-test", "format", "lint", "debug", "loc" | Where-Object { $_ -like "$wordToComplete*" }
    })]
    [string]$Command
)
$ErrorActionPreference = 'Stop'
$ErrorActionPreference = 'Continue'

function Wait-ForServer {
    for ($attempt = 1; $attempt -le 30; $attempt++) {
        $previousErrorActionPreference = $ErrorActionPreference
        $ErrorActionPreference = 'Continue'
        spacetime server ping local *> $null
        $pingExitCode = $LASTEXITCODE
        $ErrorActionPreference = $previousErrorActionPreference
        if ($pingExitCode -eq 0) {
            return
        }
        Start-Sleep -Seconds 1
    }
    throw "Local SpacetimeDB server is unavailable; run 'spacetime start'."
}
switch ($Command) {
    "test" {
        Wait-ForServer
        $originalLocation = (Get-Location).Path
        try {
        Write-Output "Building module..."
        Write-Output ""
        Push-Location examples\test
        spacetime publish --yes --server local spacetimedsl
        if ($LASTEXITCODE -ne 0) { throw "spacetime publish --yes --server local spacetimedsl failed" }
        Write-Output ""

        Write-Output "Testing module..."
        Write-Output ""
        spacetime call --yes --server local spacetimedsl tester
        if ($LASTEXITCODE -ne 0) { throw "spacetime call --yes --server local spacetimedsl tester failed" }

        Write-Output "Showing logs..."
        Write-Output ""
        spacetime logs --yes --server local spacetimedsl
        if ($LASTEXITCODE -ne 0) { throw "spacetime logs for spacetimedsl failed" }
        $test_logs = spacetime logs --yes --server local spacetimedsl 2>&1
        if ($LASTEXITCODE -ne 0) { throw "spacetime logs for spacetimedsl marker check failed" }
        if (($test_logs -join [Environment]::NewLine) -notmatch 'Test executed successfully') { throw "Test marker missing from spacetimedsl logs" }
        Write-Output ""

        Write-Output "Cleaning up module..."
        Write-Output ""
        spacetime delete --yes --server local spacetimedsl
        if ($LASTEXITCODE -ne 0) { throw "spacetime delete --yes --server local spacetimedsl failed" }
        Pop-Location
        Write-Output "Building module..."
        Write-Output ""
        Push-Location examples\blackholio
        spacetime publish --yes --server local blackholio
        if ($LASTEXITCODE -ne 0) { throw "spacetime publish --yes --server local blackholio failed" }
        Write-Output ""

        Write-Output "Showing logs..."
        Write-Output ""
        spacetime logs --yes --server local blackholio
        if ($LASTEXITCODE -ne 0) { throw "spacetime logs --yes --server local blackholio failed" }
        Write-Output ""

        Write-Output "Cleaning up module..."
        Write-Output ""
        spacetime delete --yes --server local blackholio
        if ($LASTEXITCODE -ne 0) { throw "spacetime delete --yes --server local blackholio failed" }
        Pop-Location
        } finally {
            $previousErrorActionPreference = $ErrorActionPreference
            $ErrorActionPreference = 'Continue'
            spacetime delete --yes --server local spacetimedsl *> $null
            spacetime delete --yes --server local blackholio *> $null
            while ((Get-Location).Path -ne $originalLocation) {
                Pop-Location
            }
            $ErrorActionPreference = $previousErrorActionPreference
        }
    }

    "unit-test" {
        Write-Output "Snapshotting the generated code..."
        Write-Output ""
        cargo test -p spacetimedsl_derive
        if ($LASTEXITCODE -ne 0) { throw "cargo test -p spacetimedsl_derive failed" }
        Write-Output ""

        Write-Output "Checking the diagnostics for rejected tables..."
        Write-Output ""
        cargo test -p spacetimedsl-compile-tests
        if ($LASTEXITCODE -ne 0) { throw "cargo test -p spacetimedsl-compile-tests failed" }
    }

    "format" {
        cargo fmt --all
        if ($LASTEXITCODE -ne 0) { throw "cargo fmt --all failed" }

        cargo clippy --workspace --all-targets --all-features --fix --allow-dirty
        if ($LASTEXITCODE -ne 0) { throw "cargo clippy --workspace --all-targets --all-features --fix --allow-dirty failed" }
    }

    "lint" {
        cargo fmt --all -- --check
        if ($LASTEXITCODE -ne 0) { throw "cargo fmt --all -- --check failed" }
        cargo clippy --workspace --all-targets --all-features -- -D warnings
        if ($LASTEXITCODE -ne 0) { throw "cargo clippy --workspace --all-targets --all-features -- -D warnings failed" }
    }

    "debug" {
        Push-Location examples\test
        $previousRustflags = $env:RUSTFLAGS
        try {
        $env:RUSTFLAGS = "-Zmacro-backtrace"
        cargo +nightly expand > ..\..\debug-helper\output\lib.expanded.rs
        if ($LASTEXITCODE -ne 0) { throw 'cargo expand failed' }
        } finally { $env:RUSTFLAGS = $previousRustflags }
        Push-Location ..\..\debug-helper
        cargo run -- ..\examples\test\src output
        Pop-Location
    }

    "loc" {
        $files = Get-ChildItem -Path . -Filter "*.rs" -Recurse -File | Where-Object {
            $_.FullName -like "*\src\*"
        } | ForEach-Object {
            $lineCount = (Get-Content $_.FullName | Measure-Object -Line).Lines

            $relativePath = $_.FullName.Replace("$PWD\", "")
            $firstDir = $relativePath.Split('\')[0]
            $pathWithoutFirstDir = $relativePath.Substring($firstDir.Length + 1)

            if ($pathWithoutFirstDir.StartsWith("src\")) {
                $pathWithoutFirstDir = $pathWithoutFirstDir.Substring(4)
            }

            $secondDir = if ($pathWithoutFirstDir.Contains('\')) {
                $pathWithoutFirstDir.Split('\')[0]
            } else {
                ""
            }

            [PSCustomObject]@{
                Lines = $lineCount
                Path = $relativePath
                FirstDir = $firstDir
                SecondDir = $secondDir
                PathWithoutFirstDir = $pathWithoutFirstDir
            }
        } | Sort-Object -Property FirstDir, SecondDir, @{Expression = {$_.Lines}; Descending = $true}

        $maxLineLength = ($files | ForEach-Object { $_.Lines.ToString().Length } | Measure-Object -Maximum).Maximum

        $currentGroup = $null
        $files | ForEach-Object {
            if ($currentGroup -ne $_.FirstDir) {
                if ($currentGroup -ne $null) {
                    Write-Output ""
                }
                Write-Output "$($_.FirstDir):"
                $currentGroup = $_.FirstDir
            }

            $paddedLines = $_.Lines.ToString().PadLeft($maxLineLength)
            Write-Output "$paddedLines $($_.PathWithoutFirstDir)"
        }

        $total = ($files | Where-Object { $_.FirstDir -in @("src", "derive-input", "derive") } | Measure-Object -Property Lines -Sum).Sum
        Write-Output "Total: $total"

        Write-Output ""
    }

    default {
        Write-Output "Usage: .\x.ps1 {test|unit-test|format|lint|debug|loc}"
        Write-Output ""
        Write-Output "Commands:"
        Write-Output "  test      - Publish and test the test module, then publish blackholio"
        Write-Output "  unit-test - Run the snapshot and compile tests of the generator"
        Write-Output "  format    - Format the code and apply clippy fixes"
        Write-Output "  lint      - Check formatting and lint the whole workspace"
        Write-Output "  debug     - Expand macros and generate AST output"
        Write-Output "  loc       - Count lines of Rust code grouped by directory"
        exit 1
    }
}
