# This file is generated by gen-x.sh. Do not change it directly.

#Requires -Version 7
# PowerShell 7: Windows PowerShell 5.1 turns a native command's stderr into a terminating
# error under `$ErrorActionPreference = 'Stop'`, which would end the server wait loop.

param(
    [Parameter(Position=0)]
    [ArgumentCompleter({
        param($commandName, $parameterName, $wordToComplete)
        "test", "unit-test", "format", "lint", "debug", "loc" | Where-Object { $_ -like "$wordToComplete*" }
    })]
    [string]$Command
)

$ErrorActionPreference = 'Stop'

# A thrown error ends the script with exit code 1, so callers can rely on `$LASTEXITCODE`.
trap {
    [Console]::Error.WriteLine("x.ps1 $Command failed: $_")
    exit 1
}

switch ($Command) {
    "test" {
        Write-Output "Waiting for the local server..."
        $deadline = (Get-Date).AddSeconds(30)
        while ($true) {
            spacetime server ping local *> $null
            if ($LASTEXITCODE -eq 0) { break }
            if ((Get-Date) -gt $deadline) {
                throw "The local server is still unreachable after 30 seconds. Start it with 'spacetime start'."
            }
            Start-Sleep -Seconds 1
        }
        Write-Output ""

        Push-Location examples\test
        try {
            Write-Output "Building module..."
            Write-Output ""
            spacetime publish --yes --server local spacetimedsl
            if ($LASTEXITCODE -ne 0) { throw "'spacetime publish --yes --server local spacetimedsl' failed with exit code $LASTEXITCODE." }
            Write-Output ""

            Write-Output "Testing module..."
            Write-Output ""
            spacetime call --yes --server local spacetimedsl tester
            $testerExitCode = $LASTEXITCODE

            Write-Output "Showing logs..."
            Write-Output ""
            $logs = spacetime logs --yes --server local spacetimedsl
            if ($LASTEXITCODE -ne 0) { throw "'spacetime logs --yes --server local spacetimedsl' failed with exit code $LASTEXITCODE." }
            $logs
            Write-Output ""
            if ($testerExitCode -ne 0) {
                throw "'spacetime call --yes --server local spacetimedsl tester' failed with exit code $testerExitCode."
            }
            if (-not ($logs | Select-String -SimpleMatch "Test executed successfully" -Quiet)) {
                throw "The logs of spacetimedsl do not contain 'Test executed successfully'."
            }

            Write-Output "Cleaning up module..."
            Write-Output ""
            spacetime delete --yes --server local spacetimedsl
            if ($LASTEXITCODE -ne 0) { throw "'spacetime delete --yes --server local spacetimedsl' failed with exit code $LASTEXITCODE." }
        } catch {
            spacetime delete --yes --server local spacetimedsl *> $null
            throw
        } finally {
            Pop-Location
        }

        Push-Location examples\blackholio
        try {
            Write-Output "Building module..."
            Write-Output ""
            spacetime publish --yes --server local blackholio
            if ($LASTEXITCODE -ne 0) { throw "'spacetime publish --yes --server local blackholio' failed with exit code $LASTEXITCODE." }
            Write-Output ""

            Write-Output "Showing logs..."
            Write-Output ""
            spacetime logs --yes --server local blackholio
            if ($LASTEXITCODE -ne 0) { throw "'spacetime logs --yes --server local blackholio' failed with exit code $LASTEXITCODE." }
            Write-Output ""

            Write-Output "Cleaning up module..."
            Write-Output ""
            spacetime delete --yes --server local blackholio
            if ($LASTEXITCODE -ne 0) { throw "'spacetime delete --yes --server local blackholio' failed with exit code $LASTEXITCODE." }
        } catch {
            spacetime delete --yes --server local blackholio *> $null
            throw
        } finally {
            Pop-Location
        }
    }

    "unit-test" {
        Write-Output "Snapshotting the generated code..."
        Write-Output ""
        cargo test -p spacetimedsl_derive
        if ($LASTEXITCODE -ne 0) { throw "'cargo test -p spacetimedsl_derive' failed with exit code $LASTEXITCODE." }
        Write-Output ""

        Write-Output "Checking the diagnostics for rejected tables..."
        Write-Output ""
        cargo test -p spacetimedsl-compile-tests
        if ($LASTEXITCODE -ne 0) { throw "'cargo test -p spacetimedsl-compile-tests' failed with exit code $LASTEXITCODE." }
    }

    "format" {
        cargo +nightly fmt --all -- --config imports_granularity=One,group_imports=One
        if ($LASTEXITCODE -ne 0) { throw "'cargo +nightly fmt --all -- --config imports_granularity=One,group_imports=One' failed with exit code $LASTEXITCODE." }

        cargo clippy --workspace --all-targets --all-features --fix --allow-dirty
        if ($LASTEXITCODE -ne 0) { throw "'cargo clippy --workspace --all-targets --all-features --fix --allow-dirty' failed with exit code $LASTEXITCODE." }
    }

    "lint" {
        cargo fmt --all -- --check
        if ($LASTEXITCODE -ne 0) { throw "'cargo fmt --all -- --check' failed with exit code $LASTEXITCODE." }

        cargo clippy --workspace --all-targets --all-features -- -D warnings
        if ($LASTEXITCODE -ne 0) { throw "'cargo clippy --workspace --all-targets --all-features -- -D warnings' failed with exit code $LASTEXITCODE." }
    }

    "debug" {
        $previousRustFlags = $env:RUSTFLAGS
        Push-Location examples\test
        try {
            $env:RUSTFLAGS = "-Zmacro-backtrace"
            cargo +nightly expand > ..\..\debug-helper\output\lib.expanded.rs
            if ($LASTEXITCODE -ne 0) { throw "'cargo +nightly expand' failed with exit code $LASTEXITCODE." }
        } finally {
            $env:RUSTFLAGS = $previousRustFlags
            Pop-Location
        }
        Push-Location debug-helper
        try {
            cargo run -- ..\examples\test\src output
            if ($LASTEXITCODE -ne 0) { throw "'cargo run -- ..\examples\test\src output' failed with exit code $LASTEXITCODE." }
        } finally {
            Pop-Location
        }
    }

    "loc" {
        # Get all .rs files recursively from the current directory
        $files = Get-ChildItem -Path . -Filter "*.rs" -Recurse -File | Where-Object {
            $_.FullName -like "*\src\*"
        } | ForEach-Object {
            # Count lines in each file
            $lineCount = (Get-Content $_.FullName | Measure-Object -Line).Lines

            # Create a custom object with line count and relative path
            $relativePath = $_.FullName.Replace("$PWD\", "")
            $firstDir = $relativePath.Split('\')[0]
            $pathWithoutFirstDir = $relativePath.Substring($firstDir.Length + 1)

            # Remove 'src\' prefix if present
            if ($pathWithoutFirstDir.StartsWith("src\")) {
                $pathWithoutFirstDir = $pathWithoutFirstDir.Substring(4)
            }

            # Extract second directory (first segment after removing first dir and src)
            $secondDir = if ($pathWithoutFirstDir.Contains('\')) {
                $pathWithoutFirstDir.Split('\')[0]
            } else {
                ""
            }

            [PSCustomObject]@{
                Lines = $lineCount
                Path = $relativePath
                FirstDir = $firstDir
                SecondDir = $secondDir
                PathWithoutFirstDir = $pathWithoutFirstDir
            }
        } | Sort-Object -Property FirstDir, SecondDir, @{Expression = {$_.Lines}; Descending = $true}

        # Find the maximum line count length for padding
        $maxLineLength = ($files | ForEach-Object { $_.Lines.ToString().Length } | Measure-Object -Maximum).Maximum

        # Print with aligned paths, grouped by first directory
        $currentGroup = $null
        $files | ForEach-Object {
            # Print group header when directory changes
            if ($currentGroup -ne $_.FirstDir) {
                if ($currentGroup -ne $null) {
                    Write-Output ""
                }
                Write-Output "$($_.FirstDir):"
                $currentGroup = $_.FirstDir
            }

            # Print in the format: {lines_of_code} {path_without_first_dir} with padding
            $paddedLines = $_.Lines.ToString().PadLeft($maxLineLength)
            Write-Output "$paddedLines $($_.PathWithoutFirstDir)"
        }

        # Sum lines for src, derive-input, derive
        $total = ($files | Where-Object { $_.FirstDir -in @("src", "derive-input", "derive") } | Measure-Object -Property Lines -Sum).Sum
        Write-Output "Total: $total"

        # Add final newline
        Write-Output ""
    }

    default {
        Write-Output "Usage: .\x.ps1 {test|unit-test|format|lint|debug|loc}"
        Write-Output ""
        Write-Output "Commands:"
        Write-Output "  test      - Publish and test the 'test' module (fails unless its logs show success), then publish 'blackholio'"
        Write-Output "  unit-test - Run the snapshot and compile tests of the generator"
        Write-Output "  format    - Format the code and apply clippy fixes"
        Write-Output "  lint      - Check formatting and fail on any clippy warning, as CI does"
        Write-Output "  debug     - Expand macros and generate AST output"
        Write-Output "  loc       - Count lines of Rust code grouped by directory"
        exit 1
    }
}
