#!/bin/bash

# This file is generated by gen-x.sh. Do not change it directly.

set -euo pipefail

case "${1:-}" in
    test)
        echo "Waiting for the local server..."
        deadline=$((SECONDS + 30))
        until spacetime server ping local > /dev/null 2>&1; do
            if [ "$SECONDS" -ge "$deadline" ]; then
                echo "The local server is still unreachable after 30 seconds. Start it with 'spacetime start'." >&2
                exit 1
            fi
            sleep 1
        done
        echo

        echo "Building module..."
        echo
        pushd examples/test > /dev/null
        trap 'spacetime delete --yes --server local spacetimedsl > /dev/null 2>&1 || true' EXIT
        spacetime publish --yes --server local spacetimedsl
        echo

        echo "Testing module..."
        echo
        tester_exit_code=0
        spacetime call --yes --server local spacetimedsl tester || tester_exit_code=$?

        echo "Showing logs..."
        echo
        logs=$(spacetime logs --yes --server local spacetimedsl)
        echo "$logs"
        echo
        if [ "$tester_exit_code" -ne 0 ]; then
            echo "'spacetime call --yes --server local spacetimedsl tester' failed with exit code $tester_exit_code." >&2
            exit 1
        fi
        if ! grep -qF "Test executed successfully" <<< "$logs"; then
            echo "The logs of spacetimedsl do not contain 'Test executed successfully'." >&2
            exit 1
        fi

        echo "Cleaning up module..."
        echo
        spacetime delete --yes --server local spacetimedsl
        trap - EXIT
        popd > /dev/null

        echo "Building module..."
        echo
        pushd examples/blackholio > /dev/null
        trap 'spacetime delete --yes --server local blackholio > /dev/null 2>&1 || true' EXIT
        spacetime publish --yes --server local blackholio
        echo

        echo "Showing logs..."
        echo
        spacetime logs --yes --server local blackholio
        echo

        echo "Cleaning up module..."
        echo
        spacetime delete --yes --server local blackholio
        trap - EXIT
        popd > /dev/null
        ;;

    unit-test)
        echo "Snapshotting the generated code..."
        echo
        cargo test -p spacetimedsl_derive
        echo

        echo "Checking the diagnostics for rejected tables..."
        echo
        cargo test -p spacetimedsl-compile-tests
        ;;

    format)
        cargo fmt --all

        cargo clippy --workspace --all-targets --all-features --fix --allow-dirty
        ;;

    debug)
        pushd examples/test > /dev/null
        RUSTFLAGS="-Zmacro-backtrace" cargo +nightly expand > ../../debug-helper/output/lib.expanded.rs
        popd > /dev/null
        pushd debug-helper > /dev/null
        cargo run -- ../examples/test/src output
        popd > /dev/null
        ;;

    loc)
        # Get all .rs files recursively from src directories and count lines
        while IFS= read -r file; do
            # Get line count
            lines=$(wc -l < "$file")

            # Get relative path
            rel_path="${file#./}"

            # Extract first directory
            first_dir="${rel_path%%/*}"

            # Get path without first directory
            path_without_first="${rel_path#*/}"

            # Remove src/ prefix if present
            if [[ "$path_without_first" == src/* ]]; then
                path_without_first="${path_without_first#src/}"
            fi

            # Store for grouping
            echo "$first_dir|$lines|$path_without_first"
        done < <(find . -path "*/src/*.rs" -type f) | sort -t'|' -k1,1 -k2,2nr | {
            current_group=""
            total=0

            while IFS='|' read -r first_dir lines path_without_first; do
                # Track total for src, derive-input, derive
                if [[ "$first_dir" == "src" || "$first_dir" == "derive-input" || "$first_dir" == "derive" ]]; then
                    total=$((total + lines))
                fi

                # Print group header when directory changes
                if [[ "$current_group" != "$first_dir" ]]; then
                    if [[ -n "$current_group" ]]; then
                        echo
                    fi
                    echo "$first_dir:"
                    current_group="$first_dir"
                fi

                # Print with padding
                printf "%6d %s\n" "$lines" "$path_without_first"
            done

            echo
            echo "Total: $total"
            echo
        }
        ;;

    *)
        echo "Usage: ./x {test|unit-test|format|debug|loc}"
        echo
        echo "Commands:"
        echo "  test      - Build, test, show logs, and clean up the module"
        echo "  unit-test - Run the snapshot and compile tests of the generator"
        echo "  format    - Run cargo fmt check and clippy fixes"
        echo "  debug     - Expand macros and generate AST output"
        echo "  loc       - Count lines of Rust code grouped by directory"
        exit 1
        ;;
esac
