#!/bin/bash

# This file is generated by gen-x.sh. Do not change it directly.
set -euo pipefail

wait_for_server() {
    for attempt in {1..30}; do
        if spacetime server ping local >/dev/null 2>&1; then
            return
        fi
        sleep 1
    done
    echo "Local SpacetimeDB server is unavailable; run 'spacetime start'." >&2
    return 1
}
case "$1" in
    test)
        wait_for_server
        cleanup_modules() {
            spacetime delete --yes --server local spacetimedsl >/dev/null 2>&1 || true
            spacetime delete --yes --server local blackholio >/dev/null 2>&1 || true
        }
        trap cleanup_modules EXIT
        echo "Building module..."
        echo
        pushd examples/test > /dev/null
        spacetime publish --yes --server local spacetimedsl
        echo

        echo "Testing module..."
        echo
        spacetime call --yes --server local spacetimedsl tester

        echo "Showing logs..."
        echo
        test_logs=$(spacetime logs --yes --server local spacetimedsl)
        printf '%s\n' "$test_logs"
        grep -Fq 'Test executed successfully' <<< "$test_logs" || { echo "Test marker missing from spacetimedsl logs" >&2; exit 1; }
        echo

        echo "Cleaning up module..."
        echo
        spacetime delete --yes --server local spacetimedsl
        popd > /dev/null
        echo "Building module..."
        echo
        pushd examples/blackholio > /dev/null
        spacetime publish --yes --server local blackholio
        echo

        echo "Showing logs..."
        echo
        spacetime logs --yes --server local blackholio
        echo

        echo "Cleaning up module..."
        echo
        spacetime delete --yes --server local blackholio
        popd > /dev/null
        ;;

    unit-test)
        echo "Snapshotting the generated code..."
        echo
        cargo test -p spacetimedsl_derive
        echo

        echo "Checking the diagnostics for rejected tables..."
        echo
        cargo test -p spacetimedsl-compile-tests
        ;;

    format)
        cargo fmt --all

        cargo clippy --workspace --all-targets --all-features --fix --allow-dirty
        ;;

    lint)
        cargo fmt --all -- --check
        cargo clippy --workspace --all-targets --all-features -- -D warnings
        ;;

    debug)
        pushd examples/test > /dev/null
        RUSTFLAGS="-Zmacro-backtrace" cargo +nightly expand > ../../debug-helper/output/lib.expanded.rs
        pushd ../../debug-helper > /dev/null
        cargo run -- ../examples/test/src output
        popd > /dev/null
        ;;

    loc)
        while IFS= read -r file; do
            lines=$(wc -l < "$file")

            rel_path="${file#./}"

            first_dir="${rel_path%%/*}"

            path_without_first="${rel_path#*/}"

            if [[ "$path_without_first" == src/* ]]; then
                path_without_first="${path_without_first#src/}"
            fi

            echo "$first_dir|$lines|$path_without_first"
        done < <(find . -path "*/src/*.rs" -type f) | sort -t'|' -k1,1 -k2,2nr | {
            current_group=""
            total=0

            while IFS='|' read -r first_dir lines path_without_first; do
                # Track total for src, derive-input, derive
                if [[ "$first_dir" == "src" || "$first_dir" == "derive-input" || "$first_dir" == "derive" ]]; then
                    total=$((total + lines))
                fi

                # Print group header when directory changes
                if [[ "$current_group" != "$first_dir" ]]; then
                    if [[ -n "$current_group" ]]; then
                        echo
                    fi
                    echo "$first_dir:"
                    current_group="$first_dir"
                fi

                # Print with padding
                printf "%6d %s\n" "$lines" "$path_without_first"
            done

            echo
            echo "Total: $total"
            echo
        }
        ;;

    *)
        echo "Usage: ./x {test|unit-test|format|lint|debug|loc}"
        echo
        echo "Commands:"
        echo "  test      - Publish and test the test module, then publish blackholio"
        echo "  unit-test - Run the snapshot and compile tests of the generator"
        echo "  format    - Format the code and apply clippy fixes"
        echo "  lint      - Check formatting and lint the whole workspace"
        echo "  debug     - Expand macros and generate AST output"
        echo "  loc       - Count lines of Rust code grouped by directory"
        exit 1
        ;;
esac
