//! A wrapper type written by hand, rather than generated by `#[create_wrapper]`.

use crate::spacetimedsl::prelude::*;
use std::fmt;

#[derive(SpacetimeType, Clone, Debug, PartialEq, PartialOrd)]
pub struct Temperature {
    celsius: i32,
}

impl Wrapper<i32> for Temperature {
    fn new(celsius: i32) -> Temperature {
        Temperature { celsius }
    }

    fn value(&self) -> i32 {
        self.celsius
    }
}

impl fmt::Display for Temperature {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(formatter, "{} °C", self.celsius)
    }
}

pub(crate) fn run_tests<T: WriteContext>(_dsl: &DSL<'_, T>) -> Result<(), String> {
    let temperature = Temperature::new(21);

    if temperature.value().ne(&21) {
        return Err(
            "A hand-written wrapper should give back the value it was created with!".to_string(),
        );
    }

    Ok(())
}
