[package]
authors = ["Tamaro Skaljic<mail@tamaro-skaljic.de>"]
name = "spacetimedsl_derive"
version = "0.22.0"
edition = "2024"
description = "Macros to extend SpacetimeDSL. You shouldn't depend on this directly and instead use the spacetimedsl crate."
documentation = "https://docs.rs/spacetimedsl_derive"
license = "MIT OR Apache-2.0"
repository = "https://github.com/tamaro-skaljic/SpacetimeDSL/tree/main/derive"
publish = true
include = ["/src/**"]
keywords = ["dsl", "spacetime", "macro", "codegen", "boilerplate"]
readme = "../README.md"

[lib]
proc-macro = true

[dependencies]
ident_case.workspace = true
proc-macro2.workspace = true
syn = { workspace = true, default-features = true }
quote.workspace = true
rust-format.workspace = true
spacetimedsl_derive-input.workspace = true

[dev-dependencies]
insta.workspace = true
