[package]
name = "spacetimedsl_blackholio"
version = "0.19.1"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
# https://crates.io/crates/spacetimedb Easy support for interacting between SpacetimeDB and Rust.
spacetimedb = { version = "2.0.2", features = ["unstable"] }

# https://crates.io/crates/spacetimedsl Ergonomic DSL for SpacetimeDB
spacetimedsl = { version = "0.19.1", path = "../.." }

# https://crates.io/crates/log A lightweight logging facade for Rust
log = "0.4"
