//! Covers `#[index(hash)]` and the multi-column `hash(columns = [...])` form - the third
//! index kind beside btree and direct, and the only one no example module uses.
//!
//! The snapshots pin one defect this fixture uncovered, so they do *not* read like their
//! btree counterparts:
//!
//! - A single-column hash index is never moved onto its column, because the extraction
//!   loop at `db/column.rs:63` matches only `BTreeSingleColumn` and `Direct`. It stays in
//!   `multi_column_indices` and is generated by the multi-column path, which is why
//!   `device_id` gets an `update_session_by_device_id` that the equally unique
//!   `direct_index` and `unique_single_column_index` columns do not get.

#[spacetimedsl::dsl(plural_name = sessions, method(update = true))]
#[spacetimedb::table(
    accessor = session,
    index(accessor = region_and_shard, hash(columns = [region_id, shard_id])),
    public,
)]
pub struct Session {
    #[primary_key]
    #[auto_inc]
    #[create_wrapper]
    id: u64,

    #[index(hash)]
    pub token: String,

    #[index(hash)]
    #[unique]
    pub device_id: u64,

    pub region_id: u64,

    pub shard_id: u64,
}
