pub use itertools;
pub use spacetimedsl_derive::{SpacetimeDSL, dsl, hook};
use std::fmt::Display;

pub mod as_anonymous_view_context;
pub mod as_reducer_context;
pub mod as_view_context;
pub mod get_auth;
pub mod get_connection_id;
pub mod get_immutable_database;
pub mod get_module_identity;
pub mod get_mutable_database;
pub mod get_random;
pub mod get_random_number_generator;
pub mod get_sender;
pub mod get_timestamp;
pub mod new_uuid;

pub mod delete;
pub mod error;

/// Every runtime item a module or its generated code uses, listed once. The crate root and the
/// module `spacetimedsl!()` generates re-export it, and so does the prelude of that module.
pub mod prelude {
    pub use crate::as_anonymous_view_context::AsAnonymousViewContext;
    pub use crate::as_reducer_context::AsReducerContext;
    pub use crate::as_view_context::AsViewContext;
    pub use crate::delete::{
        DeletionResult, DeletionResultEntry, OnDeleteStrategy, OnDeleteStrategyFailure,
    };
    pub use crate::error::{ReferenceIntegrityViolationError, SpacetimeDSLError};
    pub use crate::get_auth::GetAuth;
    pub use crate::get_connection_id::GetConnectionId;
    pub use crate::get_immutable_database::GetImmutableDatabase;
    pub use crate::get_module_identity::GetModuleIdentity;
    pub use crate::get_mutable_database::GetMutableDatabase;
    pub use crate::get_random::GetRandom;
    pub use crate::get_random_number_generator::GetRandomNumberGenerator;
    pub use crate::get_sender::GetSender;
    pub use crate::get_timestamp::GetTimestamp;
    pub use crate::itertools::Itertools;
    pub use crate::new_uuid::NewUUID;
    pub use crate::{Context, ReadContext, Wrapper, WriteContext};
}

pub use prelude::*;

pub(crate) enum ContextType {
    AnonymousView,
    Reducer,
    Transaction,
    View,
}

pub(crate) fn get_err(msg: &str, ctx: ContextType) -> SpacetimeDSLError {
    crate::SpacetimeDSLError::Error(format!(
        "{msg}. Tried to access from {} Context.",
        match ctx {
            ContextType::AnonymousView => "Anonymous View",
            ContextType::Reducer => "Reducer",
            ContextType::Transaction => "Transaction",
            ContextType::View => "View",
        }
    ))
}

pub trait Context:
    GetAuth
    + GetConnectionId
    + GetImmutableDatabase
    + GetModuleIdentity
    + GetMutableDatabase
    + GetRandom
    + GetRandomNumberGenerator
    + GetSender
    + GetTimestamp
    + NewUUID
    + AsAnonymousViewContext
    + AsReducerContext
    + AsViewContext
{
}

pub trait WriteContext: ReadContext + Context + spacetimedb::CtxDbWrite {}

pub trait ReadContext: Context + spacetimedb::CtxDbRead {}

pub trait Wrapper<WrappedType: Clone>:
    Clone + PartialEq + PartialOrd + spacetimedb::SpacetimeType + Display
{
    fn new(value: WrappedType) -> Self;
    fn value(&self) -> WrappedType;
}

/// Invoke this macro once at the root of your crate (`lib.rs`) to create the
/// `crate::spacetimedsl` module that holds the DSL structs, constructors, and
/// all types generated by `#[dsl]` attributes.
///
/// ```rust,ignore
/// // lib.rs
/// ::spacetimedsl::spacetimedsl!();
/// ```
///
/// Then import everything you need with:
///
/// ```rust,ignore
/// use crate::spacetimedsl::prelude::*;
/// ```
#[macro_export]
macro_rules! spacetimedsl {
    () => {
        /// Generated by [`::spacetimedsl::spacetimedsl!()`]. Contains all DSL
        /// structs, constructor functions, and the prelude for this crate.
        pub mod spacetimedsl {
            // Use `::spacetimedsl::` (global path) throughout this module.
            // The local module name `spacetimedsl` creates ambiguity with `$crate` so
            // we use the explicit `::` prefix to reference the external crate.
            pub struct DSL<'a, T: ::spacetimedsl::WriteContext + ::spacetimedsl::ReadContext> {
                ctx: &'a T,
                db: &'a spacetimedb::Local,
            }

            pub fn dsl<'a, T: ::spacetimedsl::WriteContext + ::spacetimedsl::ReadContext>(
                ctx: &'a T,
            ) -> DSL<'a, T> {
                DSL {
                    ctx,
                    db: spacetimedb::CtxDbWrite::db(ctx),
                }
            }

            impl<T: ::spacetimedsl::WriteContext + ::spacetimedsl::ReadContext> DSL<'_, T> {
                pub fn dsl(&self) -> &DSL<'_, T> {
                    self
                }
                pub fn ctx(&self) -> &T {
                    self.ctx
                }
                pub fn db(&self) -> &spacetimedb::Local {
                    self.db
                }
            }

            pub struct ReadOnlyDSL<'a, T: ::spacetimedsl::ReadContext> {
                ctx: &'a T,
                db: &'a spacetimedb::LocalReadOnly,
            }

            pub fn read_only_dsl<'a, T: ::spacetimedsl::ReadContext>(
                ctx: &'a T,
            ) -> ReadOnlyDSL<'a, T> {
                ReadOnlyDSL {
                    ctx,
                    db: spacetimedb::CtxDbRead::db_read_only(ctx),
                }
            }

            impl<T: ::spacetimedsl::ReadContext> ReadOnlyDSL<'_, T> {
                pub fn dsl(&self) -> &ReadOnlyDSL<'_, T> {
                    self
                }
                pub fn ctx(&self) -> &T {
                    self.ctx
                }
                pub fn db(&self) -> &spacetimedb::LocalReadOnly {
                    self.db
                }
            }

            impl<'a, T: ::spacetimedsl::WriteContext + ::spacetimedsl::ReadContext>
                From<&'a DSL<'a, T>> for ReadOnlyDSL<'a, T>
            {
                fn from(dsl: &'a DSL<'a, T>) -> Self {
                    read_only_dsl(dsl.ctx)
                }
            }

            impl<'a, T: ::spacetimedsl::ReadContext> From<&'a ReadOnlyDSL<'a, T>>
                for ReadOnlyDSL<'a, T>
            {
                fn from(dsl: &'a ReadOnlyDSL<'a, T>) -> Self {
                    ReadOnlyDSL {
                        ctx: dsl.ctx,
                        db: dsl.db,
                    }
                }
            }

            pub struct DSLMethodHooks {}

            /// The row a `#[dsl(singleton(with_default))]` table gives when its row is absent.
            ///
            /// `get_<table>` calls this instead of failing with a not-found error, and it does
            /// not insert the result. Implement it on the table struct. Fill the injected `id`
            /// field with `0`; `get_<table>` overwrites it in any case.
            pub trait DefaultSingleton: Sized {
                fn get_default(
                    dsl: &ReadOnlyDSL<'_, impl ::spacetimedsl::ReadContext>,
                ) -> Result<Self, ::spacetimedsl::error::SpacetimeDSLError>;
            }

            #[doc(hidden)]
            pub mod internal {
                pub struct DSLInternals;
            }

            // The runtime items, reachable as `crate::spacetimedsl::X`, which is how
            // proc-macro–generated code names them.
            pub use ::spacetimedsl::prelude::*;
            pub use ::spacetimedsl::{SpacetimeDSL, delete, error, itertools};

            pub mod prelude {
                pub use ::spacetimedsl::prelude::*;

                pub use super::{
                    DSL, DSLMethodHooks, DefaultSingleton, ReadOnlyDSL, dsl, read_only_dsl,
                };

                pub use spacetimedb::{
                    AnonymousViewContext, Identity, ProcedureContext, ReducerContext, ScheduleAt,
                    SpacetimeType, Table, TimeDuration, Timestamp, ViewContext, rand::Rng,
                };
            }
        }
    };
}
